# -*- coding: utf-8 -*-
"""project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BbYJG3VUJCn5lvDeU-UQKby-nvxHoF4V
"""

import pandas as pd
df=pd.read_csv('/content/worlddata23.csv')
df.head()
df.tail()

df.head()

df.shape

df.head()

df.isnull().sum()

result=df[df['Agricultural Land( %)'].isna()][['Country','Agricultural Land( %)']]
result

df.duplicated().sum()

df.loc[df['Country']=='Republic of the Congo','Abbreviation']='COG'
df.loc[df['Country']=='Eswatini','Abbreviation']='SWZ'
df.loc[df['Country']=='Vatican City','Abbreviation']='VAT'
df.loc[df['Country']=='Republic of Ireland','Abbreviation']='IRL'
df.loc[df['Country']=='Namibia','Abbreviation']='NAM'
df.loc[df['Country']=='North Macedonia','Abbreviation']='MKD'
df.loc[df['Country']=='Palestinian National Authority','Abbreviation']='PSE'

df.isnull().sum()

df.loc[df['Country']=='Eswatini','Agricultural Land( %)']=71.05
df.loc[df['Country']=='Vatican City','Agricultural Land( %)']=0.0
df.loc[df['Country']=='Nauru','Agricultural Land( %)']=20.0
df.loc[df['Country']=='Monaco','Agricultural Land( %)']=0.0
df.loc[df['Country']=='North Macedonia','Agricultural Land( %)']=49.8
df.loc[df['Country']=='Palestinian National Authority','Agricultural Land( %)']=64.9
df.loc[df['Country']=='South Sudan','Agricultural Land( %)']=44.7

import numpy as np
df.loc[df['Country']=='Cyprus','Density\n(P/Km2)']='104'

df.isnull().sum()

df[df["Land Area(Km2)"]=='No_value']['Country']

result=df[df['Land Area(Km2)'].isna()][['Country','Land Area(Km2)']]
result

df.loc[df['Country']=='Palestinian National Authority'	,'Land Area(Km2)']= 6020

df.isnull().sum()

df.loc[df["Country"] == "Andorra", "Armed Forces size"] = 0
df.loc[df["Country"] == "Comoros", "Armed Forces size"] = 500
df.loc[df["Country"] == "Dominica", "Armed Forces size"] = 0
df.loc[df["Country"] == "Eswatini", "Armed Forces size"] = 3000
df.loc[df["Country"] == "Grenada", "Armed Forces size"] = 1200
df.loc[df["Country"] == "Vatican City", "Armed Forces size"] = 135
df.loc[df["Country"] == "Kiribati", "Armed Forces size"] = 0
df.loc[df["Country"] == "Liechtenstein", "Armed Forces size"] = 0
df.loc[df["Country"] == "Marshall Islands", "Armed Forces size"] = 0
df.loc[df["Country"] == "Federated States of Micronesia", "Armed Forces size"] = 0
df.loc[df["Country"] == "Monaco", "Armed Forces size"] = 250
df.loc[df["Country"] == "Nauru", "Armed Forces size"] = 0
df.loc[df["Country"] == "North Macedonia", "Armed Forces size"] = 16000
df.loc[df["Country"] == "Palau", "Armed Forces size"] = 0
df.loc[df["Country"] == "Palestinian National Authority", "Armed Forces size"] = 30000
df.loc[df["Country"] == "Saint Kitts and Nevis", "Armed Forces size"] = 300
df.loc[df["Country"] == "Saint Lucia", "Armed Forces size"] = 1000
df.loc[df["Country"] == "Saint Vincent and the Grenadines", "Armed Forces size"] = 1000
df.loc[df["Country"] == "Samoa", "Armed Forces size"] = 0
df.loc[df["Country"] == "San Marino", "Armed Forces size"] = 100
df.loc[df["Country"] == "Solomon Islands", "Armed Forces size"] = 0
df.loc[df["Country"] == "Tonga", "Armed Forces size"] = 500
df.loc[df["Country"] == "Tuvalu", "Armed Forces size"] = 0
df.loc[df["Country"] == "Vanuatu", "Armed Forces size"] = 300

df[df["Country"] == 'North Macedonia']

result=df[df['Birth Rate'].isna()][['Country','Birth Rate']]
result

df.loc[df["Country"]=='Eswatini','Birth Rate']=22.8

df.loc[df['Country']=='Vatican City','Birth Rate']=0.0
df.loc[df['Country']=='Nauru','Birth Rate']=20.7
df.loc[df['Country']=='North Macedonia','Birth Rate']=9.2
df.loc[df['Country']=='Palestinian National Authority','Birth Rate']=24.42
df.loc[df['Country']=='Tuvalu','Birth Rate']=23.0

df.isnull().sum()

result=df[df['Calling Code'].isnull()][['Country','Calling Code']]
result

df.loc[df['Country']=='Palestinian National Authority','Calling Code']=970

result=df[df['Capital/Major City'].isnull()][['Country','Capital/Major City']]
result

df.loc[df['Country']=='Palestinian National Authority','Capital/Major City']='Ramallah'
df.loc[df['Country']=='Libya','Capital/Major City']='Tripoli'
df.loc[df['Country']=='Singapore','Capital/Major City']='Singapore'

df.isnull().sum()

result=df[df['Co2-Emissions'].isnull()][['Country','Co2-Emissions']]
result

df.loc[df['Country']=='Eswatini','Co2-Emissions']=1390
df.loc[df['Country']=='Vatican City','Co2-Emissions']=15.89
df.loc[df['Country']=='Nauru','Co2-Emissions']=80
df.loc[df['Country']=='North Macedonia','Co2-Emissions']=8764000
df.loc[df['Country']=='Palestinian National Authority','Co2-Emissions']=6640
df.loc[df['Country']=='San Marino','Co2-Emissions']=12283

df.loc[df['Country']=='Monaco','Co2-Emissions']=282427

df.isnull().sum()

result=df[df['CPI'].isnull()][['Country','CPI']]
result

df.info('/content/worlddata23.csv')

countries_starting_with_s = df[df['Country'].str.startswith('S')]['Country']
print(countries_starting_with_s)

df["Country"] = df["Country"].replace("S�����������" , "Sao Tome and Principe")

countries_starting_with_s = df[df['Capital/Major City'].str.startswith('S')]['Capital/Major City']
print(countries_starting_with_s)

df['Capital/Major City'] =df['Capital/Major City'].replace('San Jos������','San José')
df['Capital/Major City'] = df['Capital/Major City'].replace('S����','São Tomé')

s=df[df['Capital/Major City'].str.contains('�')]['Capital/Major City']
print(s)

df['Capital/Major City'] =df['Capital/Major City'].replace('Bras���','Brasília')
df['Capital/Major City'] =df['Capital/Major City'].replace('Yaound�','Yaoundé')
df['Capital/Major City'] =df['Capital/Major City'].replace('Bogot�','Bogotá')
df['Capital/Major City'] =df['Capital/Major City'].replace('Reykjav��','Reykjavík')
df['Capital/Major City'] =df['Capital/Major City'].replace('Mal�','Malé')
df['Capital/Major City'] =df['Capital/Major City'].replace('Chi����','Chișinău')
df['Capital/Major City'] =df['Capital/Major City'].replace('Asunci��','Asunción')
df['Capital/Major City'] =df['Capital/Major City'].replace('Lom�','Lomé')
df['Capital/Major City'] =df['Capital/Major City'].replace('Nuku����','Nukuʻalofa')

df.isnull().sum()

result=df[df['Longitude'].isnull()][['Country','Longitude',]]
result

df.loc[df['Country'] == 'São Tomé and Príncipe', 'Latitude'] = 0

df.loc[df['Country'] == 'São Tomé and Príncipe', 'Longitude'] = 6

df.isnull().sum()

result=df[df['Longitude'].isnull()][['Country','Longitude']]
result

df.loc[df['Country'] == 'São Tomé and Príncipe', 'Latitude'] = 0.1864

result=df[df['Longitude'].isnull()][['Country','Longitude']]
result

df.loc[df["Country"] == "Andorra", "CPI"] = 118.3
df.loc[df["Country"] == "Belarus", "CPI"] = 13381.0
df.loc[df["Country"] == "Liechtenstein", "CPI"] = 108.5
df.loc[df["Country"] == "North Macedonia", "CPI"] = 146.2
df.loc[df["Country"] == "Palestinian National Authority", "CPI"] = 258.4
df.loc[df["Country"] == "Somalia", "CPI"] = 144.92

result=df[df['CPI'].isnull()][['Country','CPI']]
result

df['CPI'] = pd.to_numeric(df['CPI'], errors='coerce')
df['CPI'].fillna(df['CPI'].mean(), inplace=True)

df.isnull().sum()

df[df["Country"] == "North Korea"]
df[df["Country"] == "Cuba"]

df.loc[df['Country'] == 'Andorra', 'CPI Change (%)'] = 2.18
df.loc[df['Country'] == 'Liechtenstein', 'CPI Change (%)'] = -0.18
df.loc[df['Country'] == 'North Macedonia', 'CPI Change (%)'] = 3.49
df.loc[df['Country'] == 'Palestinian National Authority', 'CPI Change (%)'] = 40

df.isnull().sum()

result=df[df['Currency-Code'].isnull()][['Country','Currency-Code']]
result

df.isnull().sum()

df.drop('Calling Code',axis=1,inplace=True)

df.isnull().sum()

result=df[df['Fertility Rate'].isnull()][['Country','Fertility Rate']]
result

df.loc[df['Country']=='Eswatini','Fertility Rate']=2.75
df.loc[df['Country']=='Vatican City','Fertility Rate']=0
df.loc[df['Country']=='Monaco','Fertility Rate']=1.53
df.loc[df['Country']=='Nauru','Fertility Rate']=2.58
df.loc[df['Country']=='North Macedonia','Fertility Rate']=1.6
df.loc[df['Country']=='Palestinian National Authority','Fertility Rate']=3.44
df.loc[df['Country']=='Tuvalu','Fertility Rate']=3.14

result=df[df['Forested Area (%)'].isnull()][['Country','Forested Area (%)']]
result

df.loc[df['Country']=='Eswatini','Forested Area (%)']=29.1
df.loc[df['Country']=='Vatican City','Forested Area (%)']=0.0
df.loc[df['Country']=='Nauru','Forested Area (%)']=0.0
df.loc[df['Country']=='Monaco','Forested Area (%)']=0.0
df.loc[df['Country']=='North Macedonia','Forested Area (%)']=39.7
df.loc[df['Country']=='Palestinian National Authority','Forested Area (%)']=4.0
df.loc[df['Country']=='South Sudan','Forested Area (%)']=11.3

df.isnull().sum()

result=df[df['GDP'].isnull()][['Country','GDP']]
result

df.drop('Currency-Code',axis=1,inplace=True)

df.loc[df['Country']=='Vatican City','GDP']= 19800000
df.loc[df['Country']=='Palestinian National Authority','GDP']= 17400000000

result=df[df['Gross primary education enrollment (%)'].isnull()][['Country','Gross primary education enrollment (%)']]
result

df.loc[df['Country']=='Bosnia and Herzegovina','Gross primary education enrollment (%)']=87.82
df.loc[df['Country']=='Eswatini','Gross primary education enrollment (%)']=114.0
df.loc[df['Country']=='Vatican City','Gross primary education enrollment (%)']=0.0
df.loc[df['Country']=='Monaco','Gross primary education enrollment (%)']=144.0
df.loc[df['Country']=='North Macedonia','Gross primary education enrollment (%)']=97.49
df.loc[df['Country']=='Palestinian National Authority','Gross primary education enrollment (%)']=91.76
df.loc[df['Country']=='Nauru','Gross primary education enrollment (%)']=93.7

result=df[df['Gross tertiary education enrollment (%)'].isnull()][['Country','Gross tertiary education enrollment (%)']]
result

df.loc[df['Country']=='Eswatini','Gross tertiary education enrollment (%)']=6.0
df.loc[df['Country']=='Vatican City','Gross tertiary education enrollment (%)']=0.0
df.loc[df['Country']=='Monaco','Gross tertiary education enrollment (%)']=53.0
df.loc[df['Country']=='North Macedonia','Gross tertiary education enrollment (%)']=53.16
df.loc[df['Country']=='Palestinian National Authority','Gross tertiary education enrollment (%)']=44.98
df.loc[df['Country']=='Nauru','Gross tertiary education enrollment (%)']=0
df.loc[df['Country']=='South Sudan','Gross tertiary education enrollment (%)']=1.0
df.loc[df['Country']=='Solomom Islands','Gross tertiary education enrollment (%)']=0
df.loc[df['Country']=='Tuvalu','Gross tertiary education enrollment (%)']=0
df.loc[df['Country']=='Andorra','Gross tertiary education enrollment (%)']=34.48
df.loc[df['Country']=='Bolivia','Gross tertiary education enrollment (%)']=0

result=df[df['Infant mortality'].isnull()][['Country','Infant mortality']]
result

df.loc[df['Country']=='Eswatini','Infant mortality']=34.99
df.loc[df['Country']=='Vatican City','Infant mortality']=0.0

df.loc[df['Country']=='Nauru','Infant mortality']=7.7
df.loc[df['Country']=='North Macedonia','Infant mortality']=5.0
df.loc[df['Country']=='Palestinian National Authority','Infant mortality']=13.0

df.isnull().sum()

result=df[df['Gross tertiary education enrollment (%)'].isnull()][['Country','Gross tertiary education enrollment (%)']]
result

df.loc[df['Gross tertiary education enrollment (%)']=='Kiribati','Gross tertiary education enrollment (%)']=0
df.loc[df['Gross tertiary education enrollment (%)']=='Solomon Islands','Gross tertiary education enrollment (%)']=0

df.isnull().sum()

df.loc[df['Country']=='Liechtenstein	','Infant mortality']=4.0

df.isnull().sum()

result=df[df['Infant mortality'].isnull()][['Country','Infant mortality']]
result

df.loc[df['Country']=='Liechtenstein	','Infant mortality']=4.0

df[df["Country"] == "Kiribati"]



df[df['Country'] == 'Kiribati'][['Country', 'Gross tertiary education enrollment (%)']]

df.drop('Largest city',axis=1,inplace=True)

result=df[df['Life expectancy'].isnull()][['Country','Life expectancy']]
result

df.loc[df['Country']=='Andorra','Life expectancy']=84.04
df.loc[df['Country']=='Eswatini','Life expectancy']=64.12
df.loc[df['Country']=='Vatican City','Life expectancy']=84.16
df.loc[df['Country']=='Monaco','Life expectancy']=86.37
df.loc[df['Country']=='Nauru','Life expectancy']=62.11
df.loc[df['Country']=='North Macedonia','Life expectancy']=74.42
df.loc[df['Country']=='Palestinian National Authority','Life expectancy']=73.44
df.loc[df['Country']=='Tuvalu','Life expectancy']=67.11

result=df[df['Maternal mortality ratio'].isnull()][['Country','Maternal mortality ratio']]
result

mmr = {
    "Andorra": 11,
    "Dominica	": 36,
    "Eswatini": 118,
    "Vatican City": 0,
    "Liechtenstein": 0,
    "Marshall Islands": 155,
    "Monaco": 5,
    "Nauru": 273,
    "North Macedonia": 3,
    "Palau": 89,
    "Palestinian National Authority": 16,
    "Saint Kitts and Nevis	": 74,
    "San Marino":8,
    "Tuvalu": 170
}
for country,mm in mmr.items():
    df.loc[df["Country"] == country, "Maternal mortality ratio"] = mm

df.isnull().sum()

result=df[df['Maternal mortality ratio'].isnull()][['Country','Maternal mortality ratio']]
result

result=df[df['Minimum wage'].isnull()][['Country','Minimum wage']]
result

df.drop('Minimum wage',axis=1,inplace=True)

df.isnull().sum()

result=df[df['Out of pocket health expenditure'].isnull()][['Country','Out of pocket health expenditure']]
result

df.loc[df['Country']=='Cuba','Out of pocket health expenditure']='11.1%'
df.loc[df['Country']=='Vatican City','Out of pocket health expenditure']= 0
df.loc[df['Country']=='Liechtenstein','Out of pocket health expenditure']= 0
df.loc[df['Country']=='Nauru','Out of pocket health expenditure']= '0.5%'
df.loc[df['Country']=='North Korea','Out of pocket health expenditure']= 0
df.loc[df['Country']=='Palestinian National Authority','Out of pocket health expenditure']= '39.4%'
df.loc[df['Country']=='Soamlia','Out of pocket health expenditure']= '42.14%'

df.isnull().sum()

result=df[df['Out of pocket health expenditure'].isnull()][['Country','Out of pocket health expenditure']]
result

result=df[df['Physicians per thousand'].isnull()][['Country','Physicians per thousand']]
result

df.loc[df['Country']=='Eswatini','Physicians per thousand']=0.14
df.loc[df['Country']=='Vatican City','Physicians per thousand']=0
df.loc[df['Country']=='Liechtenstein','Physicians per thousand']=5.5
df.loc[df['Country']=='Nauru','Physicians per thousand']=1.39
df.loc[df['Country']=='North Macedonia','Physicians per thousand']=3
df.loc[df['Country']=='Palestinian National Authority','Physicians per thousand']=37.3
df.loc[df['Country']=='South Sudan','Physicians per thousand']=0.043

result=df[df['Population'].isnull()][['Country','Population']]
result

df.loc[df['Population']=='Palestinian National Authority','Population']=5170000

result=df[df['Population: Labor force participation (%)'].isnull()][['Country','Population: Labor force participation (%)']]
result

df.loc[df['Country']=='Andorra','Population: Labor force participation (%)']='82.6%'
df.loc[df['Country']=='Antigua and Barbuda	','Population: Labor force participation (%)']='72.1%'
df.loc[df['Country']=='Dominica	','Population: Labor force participation (%)']='43.2%'
df.loc[df['Country']=='Eswatini','Population: Labor force participation (%)']='50.8%'
df.loc[df['Country']=='Grenada','Population: Labor force participation (%)']='66.38%'
df.loc[df['Country']=='Vatican City','Population: Labor force participation (%)']=0
df.loc[df['Country']=='Kiribati','Population: Labor force participation (%)']='48.1%'
df.loc[df['Country']=='Liechtenstein','Population: Labor force participation (%)']='77.8%'
df.loc[df['Country']=='Marshall Islands','Population: Labor force participation (%)']='49.5%'
df.loc[df['Country']=='Federated States of Micronesia','Population: Labor force participation (%)']=0
df.loc[df['Country']=='Nauru','Population: Labor force participation (%)']= '63%'
df.loc[df['Country']=='North Macedonia','Population: Labor force participation (%)']='28.31%'
df.loc[df['Country']=='Palau','Population: Labor force participation (%)']='67%'
df.loc[df['Country']=='Palestinian National Authority','Population: Labor force participation (%)']='46.10%'
df.loc[df['Country']=='Saint Kitts and Nevis','Population: Labor force participation (%)']=0
df.loc[df['Country']=='San Marino','Population: Labor force participation (%)']='57.6%'
df.loc[df['Country']=='Seychelles','Population: Labor force participation (%)']='63.31%'
df.loc[df['Country']=='Tuvalu','Population: Labor force participation (%)']='24.9%'

result=df[df['Tax revenue (%)'].isnull()][['Country','Tax revenue (%)']]
result

df.isnull().sum()

results=df[df['Gasoline Price'].isnull()][['Country','Gasoline Price']]
result

df.drop('Gasoline Price',axis=1,inplace=True)

df.isnull().sum()

result=df[df['Tax revenue (%)'].isnull()][['Country','Tax revenue (%)']]
result

df.loc[df['Country']=='Andorra','Tax revenue (%)']=0
df.loc[df['Country']=='Brunei	','Tax revenue (%)']=0
df.loc[df['Country']=='Chad','Tax revenue (%)']=0
df.loc[df['Country']=='Comoros','Tax revenue (%)']=0
df.loc[df['Country']=='Cuba','Tax revenue (%)']=0
df.loc[df['Country']=='Djibouti	','Tax revenue (%)']=0
df.loc[df['Country']=='Venezuela','Tax revenue (%)']=0
df.loc[df['Country']=='Yemen	','Tax revenue (%)']=0
df.loc[df['Country']=='Tuvalu	','Tax revenue (%)']=0
df.loc[df['Country']=='Turkmenistan	','Tax revenue (%)']=0
df.loc[df['Country']=='South Sudan','Tax revenue (%)']=0
df.loc[df['Country']=='Panama','Tax revenue (%)']='7.5%'
df.loc[df['Country']=='Palestinian National Authority','Tax revenue (%)']='21.47%'
df.loc[df['Country']=='North Macedonia','Tax revenue (%)']='17.4%'
df.loc[df['Country']=='North Korea','Tax revenue (%)']=0
df.loc[df['Country']=='Nauru','Tax revenue (%)']='44%'
df.loc[df['Country']=='Montenegro	','Tax revenue (%)']=0
df.loc[df['Country']=='Monaco','Tax revenue (%)']=0
df.loc[df['Country']=='Mauritania	','Tax revenue (%)']=0
df.loc[df['Country']=='Liechtenstein	','Tax revenue (%)']=0
df.loc[df['Country']=='Libya','Tax revenue (%)']=0
df.loc[df['Country']=='Vatican City	','Tax revenue (%)']='7%'
df.loc[df['Country']=='Haiti	','Tax revenue (%)']=0
df.loc[df['Country']=='Guyana	','Tax revenue (%)']=0
df.loc[df['Country']=='Eritrea	','Tax revenue (%)']=0
df.loc[df['Country']=='Ecuador	','Tax revenue (%)']='13%'

df.isnull().sum()

result=df[df['Tax revenue (%)'].isnull()][['Country','Tax revenue (%)']]
result

df.drop('Total tax rate',axis=1,inplace=True)

df.isnull().sum()

result=df[df['Unemployment rate'].isnull()][['Country','Unemployment rate']]
result

df.loc[df['Country']=='Andorra','Unemployment rate']='1.5%'
df.loc[df['Country']=='Antigua and Barbuda','Unemployment rate']='15.08%'
df.loc[df['Country']=='Dominica	','Unemployment rate']='13.13%'
df.loc[df['Country']=='Eswatini','Unemployment rate']='35.4%'
df.loc[df['Country']=='Grenada','Unemployment rate']='12.0%'
df.loc[df['Country']=='Vatican City','Unemployment rate']='0'
df.loc[df['Country']=='Kiribati','Unemployment rate']='8.6%'
df.loc[df['Country']=='Liechtenstein','Unemployment rate']='1.4%'
df.loc[df['Country']=='Marshall Islands','Unemployment rate']='9.8%'
df.loc[df['Country']=='Federated States of Micronesia','Unemployment rate']='16.1%'
df.loc[df['Country']=='Monaco','Unemployment rate']='2%'
df.loc[df['Country']=='Nauru','Unemployment rate']='5.1%'
df.loc[df['Country']=='North Macedonia','Unemployment rate']='13.05%'
df.loc[df['Country']=='Palau','Unemployment rate']='0.8%'
df.loc[df['Country']=='Palestinian National Authority','Unemployment rate']='26.4%'
df.loc[df['Country']=='Saint Kitts and Nevis','Unemployment rate']='5.09%'
df.loc[df['Country']=='San Marino','Unemployment rate']='4.6%'
df.loc[df['Country']=='Seychelles','Unemployment rate']='3%'
df.loc[df['Country']=='Tuvalu','Unemployment rate']='7.3%'

df.isnull().sum()

result=df[df['Urban_population'].isnull()][['Country','Urban_population']]
result

df.loc[df['Country']=='Eswatini','Urban_population']=305042
df.loc[df['Country']=='Vatican City','Urban_population']=764
df.loc[df['Country']=='Nauru','Urban_population']=11261
df.loc[df['Country']=='North Macedonia','Urban_population']=1087167
df.loc[df['Country']=='Palestinian National Authority','Urban_population']=4420000

df.isnull().sum()

# prompt: code for saving to csv and excel

df.to_csv('worlddata23_cleaned.csv', index=False)
df.to_excel('worlddata23_cleaned.xlsx', index=False)

